# Copyright (c) 2021-2026, ETH Zurich and NVIDIA CORPORATION
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Helper functions."""

from .formal_training_io import (
    FORMAL_CHECKPOINT_RUN_INSPECTION_CONTRACT,
    FORMAL_CHECKPOINT_RUN_INSPECTION_SCHEMA_VERSION,
    inspect_formal_checkpoint_run,
    validate_formal_checkpoint_run_inspection_document,
)
from .mid360_ray_time_builder import (
    MID360_NORMALIZED_SENSOR_FRAME,
    MID360_TIMESTAMP_ADAPTER_ABSOLUTE_POINTS,
    MID360_TIMESTAMP_CAPTURE_WINDOW_ONLY,
    MID360_TIMESTAMP_LIVOX_CUSTOM_MSG,
    Mid360PacketAdapter,
    Mid360PacketStats,
    Mid360PointPacket,
    Mid360RayTimeBuilderError,
    Mid360RayTimeTensorBuilder,
    StaleMid360PacketError,
    point_packet_from_livox_custom_msg_arrays,
)
from .motion_loader import AMPLoader
from .motion_loader_for_display import AMPLoaderDisplay
from .ray_time_deployment_manifest import (
    RayTimeManifestError,
    build_ray_time_deployment_manifest,
    canonical_json_bytes,
    canonical_json_sha256,
    collect_git_provenance,
    default_ray_time_channels,
    default_ray_time_mount_geometry,
    default_ray_time_proprio_terms,
    default_ray_time_tensorization,
    read_ray_time_deployment_manifest,
    serialize_ray_time_deployment_manifest,
    validate_ray_time_deployment_manifest,
    write_ray_time_deployment_manifest,
)
from .ray_time_export_attestation import (
    RAY_TIME_EXPORT_ATTESTATION_SCHEMA_NAME,
    RAY_TIME_EXPORT_ATTESTATION_SCHEMA_VERSION,
    RayTimeExportAttestationError,
    build_ray_time_export_attestation,
    capture_ray_time_checkpoint_snapshot,
    validate_ray_time_export_attestation_document,
    validate_ray_time_export_attestation,
)
from .training_receipt import (
    CHECKPOINT_EMBEDDED_RECEIPT_CONTRACT,
    CHECKPOINT_SIDECAR_CONTRACT,
    TRAINING_LAUNCH_RECEIPT_CONTRACT,
    TRAINING_RECEIPT_SCHEMA_VERSION,
    TrainingReceiptError,
    build_checkpoint_sidecar,
    build_embedded_checkpoint_receipt,
    build_training_launch_receipt,
    canonical_training_receipt_json_bytes,
    canonical_training_receipt_sha256,
    checkpoint_parent_record,
    derive_checkpoint_progress,
    parse_canonical_training_receipt_json,
    retain_regular_file,
    validate_checkpoint_progress,
    validate_checkpoint_receipt_chain,
    validate_checkpoint_sidecar,
    validate_embedded_checkpoint_receipt,
    validate_training_launch_receipt,
)

from .utils import (
    check_nan,
    get_param,
    resolve_callable,
    resolve_nn_activation,
    resolve_obs_groups,
    resolve_optimizer,
    split_and_pad_trajectories,
    unpad_trajectories,
)

__all__ = [
    "AMPLoader",
    "CHECKPOINT_EMBEDDED_RECEIPT_CONTRACT",
    "CHECKPOINT_SIDECAR_CONTRACT",
    "FORMAL_CHECKPOINT_RUN_INSPECTION_CONTRACT",
    "FORMAL_CHECKPOINT_RUN_INSPECTION_SCHEMA_VERSION",
    "MID360_NORMALIZED_SENSOR_FRAME",
    "MID360_TIMESTAMP_ADAPTER_ABSOLUTE_POINTS",
    "MID360_TIMESTAMP_CAPTURE_WINDOW_ONLY",
    "MID360_TIMESTAMP_LIVOX_CUSTOM_MSG",
    "Mid360PacketAdapter",
    "Mid360PacketStats",
    "Mid360PointPacket",
    "Mid360RayTimeBuilderError",
    "Mid360RayTimeTensorBuilder",
    "RayTimeManifestError",
    "RayTimeExportAttestationError",
    "RAY_TIME_EXPORT_ATTESTATION_SCHEMA_NAME",
    "RAY_TIME_EXPORT_ATTESTATION_SCHEMA_VERSION",
    "TRAINING_LAUNCH_RECEIPT_CONTRACT",
    "TRAINING_RECEIPT_SCHEMA_VERSION",
    "StaleMid360PacketError",
    "TrainingReceiptError",
    "build_checkpoint_sidecar",
    "build_embedded_checkpoint_receipt",
    "build_ray_time_deployment_manifest",
    "build_ray_time_export_attestation",
    "build_training_launch_receipt",
    "canonical_training_receipt_json_bytes",
    "canonical_training_receipt_sha256",
    "capture_ray_time_checkpoint_snapshot",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "check_nan",
    "checkpoint_parent_record",
    "collect_git_provenance",
    "default_ray_time_channels",
    "default_ray_time_mount_geometry",
    "default_ray_time_proprio_terms",
    "default_ray_time_tensorization",
    "get_param",
    "inspect_formal_checkpoint_run",
    "point_packet_from_livox_custom_msg_arrays",
    "derive_checkpoint_progress",
    "parse_canonical_training_receipt_json",
    "retain_regular_file",
    "resolve_callable",
    "resolve_nn_activation",
    "resolve_obs_groups",
    "resolve_optimizer",
    "read_ray_time_deployment_manifest",
    "serialize_ray_time_deployment_manifest",
    "split_and_pad_trajectories",
    "unpad_trajectories",
    "validate_ray_time_deployment_manifest",
    "validate_ray_time_export_attestation_document",
    "validate_ray_time_export_attestation",
    "validate_checkpoint_progress",
    "validate_checkpoint_receipt_chain",
    "validate_checkpoint_sidecar",
    "validate_embedded_checkpoint_receipt",
    "validate_formal_checkpoint_run_inspection_document",
    "validate_training_launch_receipt",
    "write_ray_time_deployment_manifest",
]
